### ISSUE TITLE
Timeout utility not working 

### ISSUE THREAD

**Issue by smsharma1** [ZaydH/spur#1]
Probably because sampler_stopwatch_.setTimeBound(config_.time_bound_seconds); is set before updating the config_.time_bound_seconds

**Comment by ZaydH** [comment]
@smsharma1 

I believe this issue is now fixed.  I did not see a MWE to replicate the bug and use for verification.  Can you please verify the fix in your setup using branch tree/GH-0001/timeout_broken?  

There are a couple of other miscellaneous improvements and very minor bug fixes as well.

**Comment by ZaydH** [comment]
@smsharma1 , I am going to close this case and issue an updated release. 

If you think the fix is insufficient, feel free to reopen and I am happy to look at it more.
