### ISSUE TITLE
`-count-only` argument causes crash

### ISSUE THREAD

**Issue by drautb** [ZaydH/spur#2]
**Describe the bug**
Invoking `spur` with the `-count-only` argument triggers a core dump.

**To reproduce**
1. `./build/Release/spur -d -v -count-only -cnf stroop-2-constrained.cnf`

**DIMACS formula**
[stroop-2-constrained.cnf.zip](https://github.com/ZaydH/spur/files/2859077/stroop-2-constrained.cnf.zip)

**Expected behavior**
I expected to get a solution count, rather than the program crashing.

**Error message**
```
➜  spur git:(master) ✗ ./build/Release/spur -d -v -count-only -cnf stroop-2-constrained.cnf 
WARNING: Debug mode has a fixed seed for the MPZ class.
WARNING: Debug mode uses a fixed random number seed.
terminate called after throwing an instance of 'std::length_error'
  what():  vector::reserve
[1]    10072 abort (core dumped)  ./build/Release/spur -d -v -count-only -cnf stroop-2-constrained.cnf
```

**System information**
```
➜  spur git:(master) ✗ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
➜  spur git:(master) ✗ g++ --version
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Built current `master` (2131dbaee0d057ee3f3e353d56e71cb0d69ec2a2)

**Comment by ZaydH** [comment]
Thanks for reporting this.  Can you please check now?  I did some quick tests and it looks good.  This older version of the code lacks test coverage.  My apologies for the inconvenience.

**Comment by drautb** [comment]
Works great now, thank you!
